package com.chollan.kanapa.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF00677E)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFB5EBFF)
val md_theme_light_onPrimaryContainer = Color(0xFF001F28)
val md_theme_light_secondary = Color(0xFF006684)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFBDE9FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001F2A)
val md_theme_light_tertiary = Color(0xFF00658F)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC7E7FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001E2E)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBFCFE)
val md_theme_light_onBackground = Color(0xFF191C1D)
val md_theme_light_surface = Color(0xFFFBFCFE)
val md_theme_light_onSurface = Color(0xFF191C1D)
val md_theme_light_surfaceVariant = Color(0xFFDBE4E8)
val md_theme_light_onSurfaceVariant = Color(0xFF40484B)
val md_theme_light_outline = Color(0xFF70787C)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1F2)
val md_theme_light_inverseSurface = Color(0xFF2E3132)
val md_theme_light_inversePrimary = Color(0xFF5BD5FA)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF00677E)
val md_theme_light_outlineVariant = Color(0xFFBFC8CC)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF5BD5FA)
val md_theme_dark_onPrimary = Color(0xFF003543)
val md_theme_dark_primaryContainer = Color(0xFF004E60)
val md_theme_dark_onPrimaryContainer = Color(0xFFB5EBFF)
val md_theme_dark_secondary = Color(0xFF67D3FF)
val md_theme_dark_onSecondary = Color(0xFF003546)
val md_theme_dark_secondaryContainer = Color(0xFF004D64)
val md_theme_dark_onSecondaryContainer = Color(0xFFBDE9FF)
val md_theme_dark_tertiary = Color(0xFF86CFFF)
val md_theme_dark_onTertiary = Color(0xFF00344C)
val md_theme_dark_tertiaryContainer = Color(0xFF004C6D)
val md_theme_dark_onTertiaryContainer = Color(0xFFC7E7FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1D)
val md_theme_dark_onBackground = Color(0xFFE1E3E4)
val md_theme_dark_surface = Color(0xFF191C1D)
val md_theme_dark_onSurface = Color(0xFFE1E3E4)
val md_theme_dark_surfaceVariant = Color(0xFF40484B)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC8CC)
val md_theme_dark_outline = Color(0xFF899296)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1D)
val md_theme_dark_inverseSurface = Color(0xFFE1E3E4)
val md_theme_dark_inversePrimary = Color(0xFF00677E)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF5BD5FA)
val md_theme_dark_outlineVariant = Color(0xFF40484B)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF53C9EC)
val CustomColor1 = Color(0xFF26ABCD)
val light_CustomColor1 = Color(0xFF00677E)
val light_onCustomColor1 = Color(0xFFFFFFFF)
val light_CustomColor1Container = Color(0xFFB4EBFF)
val light_onCustomColor1Container = Color(0xFF001F28)
val dark_CustomColor1 = Color(0xFF5BD5F9)
val dark_onCustomColor1 = Color(0xFF003543)
val dark_CustomColor1Container = Color(0xFF004E5F)
val dark_onCustomColor1Container = Color(0xFFB4EBFF)
